"use client";

import { useState } from "react";
import { Activity, CircleAlert, Copy, KeyRound, Link2, Play, ShieldCheck, Webhook } from "lucide-react";
import type { DeveloperIntegrationSummary } from "@/lib/developerSalesOps";

const SCOPES = ["contacts:read", "contacts:write", "inventory:read", "inventory:write", "analytics:read", "webhooks:write", "imports:write"] as const;
const EVENTS = ["lead.created", "lead.updated", "lead.note_added", "integration.sync"] as const;

export function DeveloperIntegrationsCenter({ initialData }: { initialData: DeveloperIntegrationSummary }) {
  const [data, setData] = useState(initialData);
  const [credentialName, setCredentialName] = useState("");
  const [selectedScopes, setSelectedScopes] = useState<string[]>(["contacts:read"]);
  const [webhookName, setWebhookName] = useState("");
  const [webhookUrl, setWebhookUrl] = useState("");
  const [selectedEvents, setSelectedEvents] = useState<string[]>(["lead.created", "lead.updated"]);
  const [scheduleName, setScheduleName] = useState("");
  const [sourceLabel, setSourceLabel] = useState("");
  const [scheduleId, setScheduleId] = useState("");
  const [oneTimeSecret, setOneTimeSecret] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<{ type: "error" | "success"; message: string } | null>(null);
  const [pending, setPending] = useState(false);

  async function call(path: string, method: string, body?: unknown) {
    const response = await fetch(path, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(typeof payload.error === "string" ? payload.error : "The integration action failed.");
    return payload;
  }

  async function createCredential(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; setPending(true); setFeedback(null); setOneTimeSecret(null);
    try { const payload = await call("/api/developer/integrations/credentials", "POST", { name: credentialName, scopes: selectedScopes }); setCredentialName(""); setOneTimeSecret(typeof payload.secret === "string" ? payload.secret : null); setFeedback({ type: "success", message: "Credential created. Copy the secret now; it will not be shown again." }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to create credential." }); } finally { setPending(false); }
  }

  async function createWebhook(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; setPending(true); setFeedback(null); setOneTimeSecret(null);
    try { const payload = await call("/api/developer/integrations/webhooks", "POST", { name: webhookName, endpointUrl: webhookUrl, events: selectedEvents }); setWebhookName(""); setWebhookUrl(""); setOneTimeSecret(typeof payload.secret === "string" ? payload.secret : null); setFeedback({ type: "success", message: "Webhook registered. Store the signing secret now; it will not be shown again." }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to create webhook." }); } finally { setPending(false); }
  }

  async function createSchedule(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; setPending(true); setFeedback(null);
    try { const payload = await call("/api/developer/integrations/schedules", "POST", { name: scheduleName, sourceLabel, sourceKind: "manual_file", cadence: "manual", dryRunDefault: true, idempotencyStrategy: "source_key", conflictStrategy: "flag_for_review" }); setScheduleId(String(payload.scheduleId || "")); setScheduleName(""); setSourceLabel(""); setFeedback({ type: "success", message: "Import configuration saved. No provider has been connected." }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to create schedule." }); } finally { setPending(false); }
  }

  async function dryRun(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending || !scheduleId) return; setPending(true); setFeedback(null);
    try { await call("/api/developer/integrations/sync-runs", "POST", { scheduleId, mode: "dry_run", idempotencyKey: `manual-${Date.now()}` }); setFeedback({ type: "success", message: "Dry-run record created. No external network call was made." }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to create dry-run record." }); } finally { setPending(false); }
  }

  async function refresh() {
    const [credentials, webhooks, schedules, syncRuns] = await Promise.all([
      fetch("/api/developer/integrations/credentials", { cache: "no-store" }).then((response) => response.json()),
      fetch("/api/developer/integrations/webhooks", { cache: "no-store" }).then((response) => response.json()),
      fetch("/api/developer/integrations/schedules", { cache: "no-store" }).then((response) => response.json()),
      fetch("/api/developer/integrations/sync-runs", { cache: "no-store" }).then((response) => response.json()),
    ]);
    setData((current) => ({ ...current, credentials: Array.isArray(credentials.credentials) ? credentials.credentials : current.credentials, webhooks: Array.isArray(webhooks.webhooks) ? webhooks.webhooks : current.webhooks, schedules: Array.isArray(schedules.schedules) ? schedules.schedules : current.schedules, mappings: Array.isArray(schedules.mappings) ? schedules.mappings : current.mappings, syncRuns: Array.isArray(syncRuns.syncRuns) ? syncRuns.syncRuns : current.syncRuns, pendingWebhookDeliveries: typeof syncRuns.pendingWebhookDeliveries === "number" ? syncRuns.pendingWebhookDeliveries : current.pendingWebhookDeliveries }));
  }

  async function toggleWebhook(id: string, status: string) { try { await call(`/api/developer/integrations/webhooks/${id}`, "PATCH", { status }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to update webhook." }); } }
  async function toggleSchedule(id: string, enabled: boolean) { try { await call(`/api/developer/integrations/schedules/${id}`, "PATCH", { enabled }); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to update schedule." }); } }
  async function revokeCredential(id: string) { if (!window.confirm("Revoke this API credential? Existing requests using it will stop authenticating.")) return; try { await call(`/api/developer/integrations/credentials/${id}`, "DELETE"); await refresh(); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to revoke credential." }); } }

  return (
    <div className="space-y-5">
      <section className="rounded-3xl border border-[#d8e5a0] bg-[#f1f5d9] p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck aria-hidden="true" size={19} className="mt-0.5 shrink-0 text-[#4c5d11]" /><div><h2 className="text-sm font-semibold text-[#28300c]">Configuration-only integration foundation</h2><p className="mt-1 text-sm leading-6 text-[#4c5d11]">Credentials and webhook secrets are hashed. Webhook deliveries are recorded in a durable pending outbox; this workspace never claims delivery without a worker outcome.</p></div></div></section>
      {feedback ? <p role={feedback.type === "error" ? "alert" : "status"} className={`rounded-2xl border px-4 py-3 text-sm ${feedback.type === "error" ? "border-rose-200 bg-rose-50 text-rose-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{feedback.message}</p> : null}
      {oneTimeSecret ? <section className="rounded-2xl border border-amber-300 bg-amber-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-amber-900">Shown once</p><div className="mt-2 flex flex-wrap items-center gap-2"><code className="min-w-0 flex-1 break-all rounded-xl border border-amber-200 bg-white px-3 py-2 text-sm text-amber-950">{oneTimeSecret}</code><button type="button" onClick={() => void navigator.clipboard?.writeText(oneTimeSecret)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-amber-300 px-3 py-2 text-xs font-semibold text-amber-900 hover:bg-amber-100"><Copy aria-hidden="true" size={14} /> Copy</button></div><p className="mt-2 text-xs text-amber-800">If you leave this page before saving it, generate a new credential or webhook secret.</p></section> : null}

      <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-black/5 bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><KeyRound aria-hidden="true" size={18} className="mt-0.5 text-neutral-700" /><div><h2 className="text-sm font-semibold text-neutral-900">API credentials</h2><p className="mt-1 text-xs leading-5 text-neutral-500">Company-scoped, scope-limited, revocable. Plaintext is shown only at creation.</p></div></div><form onSubmit={createCredential} className="mt-4 space-y-3"><input required maxLength={120} value={credentialName} onChange={(event) => setCredentialName(event.target.value)} placeholder="Reporting integration" className="min-h-10 w-full rounded-xl border border-black/10 bg-neutral-50 px-3 text-sm" /><fieldset><legend className="text-[10px] font-semibold uppercase tracking-[0.15em] text-neutral-500">Scopes</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{SCOPES.map((scope) => <label key={scope} className="flex items-center gap-2 text-xs text-neutral-700"><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={(event) => setSelectedScopes((current) => event.target.checked ? [...current, scope] : current.filter((item) => item !== scope))} />{scope}</label>)}</div></fieldset><button disabled={pending} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-black px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" type="submit">Create credential</button></form><div className="mt-5 space-y-2">{data.credentials.map((credential) => <div key={credential.id} className="rounded-2xl border border-black/5 bg-neutral-50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-neutral-900">{credential.name}</p><p className="mt-1 text-xs text-neutral-500"><code>{credential.key_prefix}…</code> · {credential.scopes.join(", ")}</p></div>{credential.revoked_at ? <span className="text-[11px] font-semibold text-rose-700">Revoked</span> : <button type="button" onClick={() => void revokeCredential(credential.id)} className="text-[11px] font-semibold text-rose-700 hover:underline">Revoke</button>}</div></div>)}</div></section>

      <section className="rounded-3xl border border-black/5 bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><Webhook aria-hidden="true" size={18} className="mt-0.5 text-neutral-700" /><div><h2 className="text-sm font-semibold text-neutral-900">Webhooks</h2><p className="mt-1 text-xs leading-5 text-neutral-500">HTTPS endpoints receive queued event contracts when a delivery worker is connected.</p></div></div><form onSubmit={createWebhook} className="mt-4 space-y-3"><input required maxLength={120} value={webhookName} onChange={(event) => setWebhookName(event.target.value)} placeholder="CRM lead updates" className="min-h-10 w-full rounded-xl border border-black/10 bg-neutral-50 px-3 text-sm" /><input required type="url" pattern="https://.*" value={webhookUrl} onChange={(event) => setWebhookUrl(event.target.value)} placeholder="https://example.com/brixeler/webhook" className="min-h-10 w-full rounded-xl border border-black/10 bg-neutral-50 px-3 text-sm" /><fieldset><legend className="text-[10px] font-semibold uppercase tracking-[0.15em] text-neutral-500">Events</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{EVENTS.map((eventName) => <label key={eventName} className="flex items-center gap-2 text-xs text-neutral-700"><input type="checkbox" checked={selectedEvents.includes(eventName)} onChange={(event) => setSelectedEvents((current) => event.target.checked ? [...current, eventName] : current.filter((item) => item !== eventName))} />{eventName}</label>)}</div></fieldset><button disabled={pending} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-black px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" type="submit">Register webhook</button></form><div className="mt-5 space-y-2">{data.webhooks.map((webhook) => <div key={webhook.id} className="rounded-2xl border border-black/5 bg-neutral-50 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-neutral-900">{webhook.name}</p><p className="mt-1 truncate text-xs text-neutral-500">{webhook.endpoint_url} · {webhook.events.join(", ")}</p><p className="mt-1 text-[11px] text-neutral-400">{webhook.failure_count} recorded failure{webhook.failure_count === 1 ? "" : "s"} · {webhook.last_success_at ? `Last success ${formatDate(webhook.last_success_at)}` : "No delivery success recorded"}</p></div><button type="button" onClick={() => void toggleWebhook(webhook.id, webhook.status === "active" ? "paused" : "active")} className="shrink-0 text-[11px] font-semibold text-neutral-700 hover:underline">{webhook.status === "active" ? "Pause" : "Resume"}</button></div></div>)}</div></section></div>

      <div className="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><section className="rounded-3xl border border-black/5 bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><Link2 aria-hidden="true" size={18} className="mt-0.5 text-neutral-700" /><div><h2 className="text-sm font-semibold text-neutral-900">Scheduled import configuration</h2><p className="mt-1 text-xs leading-5 text-neutral-500">Define source and conflict behavior now; connect a provider later.</p></div></div><form onSubmit={createSchedule} className="mt-4 space-y-3"><input required maxLength={120} value={scheduleName} onChange={(event) => setScheduleName(event.target.value)} placeholder="Weekly inventory file" className="min-h-10 w-full rounded-xl border border-black/10 bg-neutral-50 px-3 text-sm" /><input required maxLength={200} value={sourceLabel} onChange={(event) => setSourceLabel(event.target.value)} placeholder="SFTP export · contract pending" className="min-h-10 w-full rounded-xl border border-black/10 bg-neutral-50 px-3 text-sm" /><p className="rounded-xl bg-neutral-50 px-3 py-2 text-xs leading-5 text-neutral-500">Manual cadence · dry run by default · source key idempotency · flag conflicts for review</p><button disabled={pending} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-black px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" type="submit">Save configuration</button></form><div className="mt-5 space-y-2">{data.schedules.map((schedule) => <div key={schedule.id} className="rounded-2xl border border-black/5 bg-neutral-50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-neutral-900">{schedule.name}</p><p className="mt-1 text-xs text-neutral-500">{schedule.source_label} · {schedule.cadence} · {schedule.dry_run_default ? "Dry run default" : "Commit default"}</p></div><button type="button" onClick={() => void toggleSchedule(schedule.id, !schedule.enabled)} className="text-[11px] font-semibold text-neutral-700 hover:underline">{schedule.enabled ? "Disable" : "Enable"}</button></div></div>)}</div></section>

      <section className="rounded-3xl border border-black/5 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><Activity aria-hidden="true" size={18} className="mt-0.5 text-neutral-700" /><div><h2 className="text-sm font-semibold text-neutral-900">Sync health & delivery log</h2><p className="mt-1 text-xs leading-5 text-neutral-500">Run metadata, idempotency keys, row counts, and conflicts stay visible.</p></div></div><span className="rounded-full bg-amber-50 px-3 py-1.5 text-[11px] font-semibold text-amber-800">{data.pendingWebhookDeliveries} webhook deliveries pending</span></div><form onSubmit={dryRun} className="mt-4 flex flex-wrap gap-2"><select required value={scheduleId} onChange={(event) => setScheduleId(event.target.value)} className="min-h-10 min-w-0 flex-1 rounded-xl border border-black/10 bg-neutral-50 px-3 text-xs"><option value="">Choose an import schedule</option>{data.schedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.name}</option>)}</select><button disabled={pending || !scheduleId} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-black/15 px-4 py-2 text-xs font-semibold text-neutral-800 disabled:opacity-50" type="submit"><Play aria-hidden="true" size={14} /> Dry run</button></form><div className="mt-5 space-y-2">{data.syncRuns.length ? data.syncRuns.slice(0, 10).map((run) => <div key={run.id} className="rounded-2xl border border-black/5 bg-neutral-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold text-neutral-900">{run.status} · {run.mode}</p><code className="text-[11px] text-neutral-500">{run.idempotency_key}</code></div><p className="mt-1 text-[11px] text-neutral-500">{run.rows_seen} rows seen · {run.rows_created} created · {run.rows_updated} updated · {run.conflict_count} conflicts · {formatDate(run.created_at)}</p>{run.error_summary ? <p className="mt-1 flex items-center gap-1 text-[11px] text-rose-700"><CircleAlert aria-hidden="true" size={12} /> {run.error_summary}</p> : null}</div>) : <p className="rounded-xl bg-neutral-50 px-3 py-4 text-xs text-neutral-500">No sync runs recorded.</p>}</div></section></div>
    </div>
  );
}

function formatDate(value: string) { const date = new Date(value); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(date) : "—"; }
