-- Security hardening for the mobile/web shared Supabase project.
-- The application writes privileged records through the RPCs below; direct
-- client table writes are intentionally reduced to the minimum required.

begin;

-- Contact requests are written/read by the server-role web API only.
alter table if exists public.developer_contact_requests enable row level security;
alter table if exists public.developer_contact_requests force row level security;
revoke all on table public.developer_contact_requests from anon, authenticated;
alter function public.touch_developer_contact_requests_updated_at() set search_path = public, extensions;

-- Agent profile edits are owner-only and cannot mutate verification/commission
-- fields from the client. Server-side verification routes retain service-role access.
alter table public.users_profile force row level security;
revoke update on table public.users_profile from anon, authenticated;
grant update (
  display_name,
  phone,
  bio,
  profile_picture_url,
  bank_name,
  bank_account_holder,
  bank_account_number,
  bank_iban,
  bank_swift_code,
  language_preference,
  notification_preferences,
  profile_visibility,
  show_earnings_on_profile,
  show_deal_count_on_profile
) on table public.users_profile to authenticated;

-- Verification documents are stored as private object paths and exposed only
-- through short-lived signed URLs generated by the server or owning agent.
update storage.buckets
set public = false,
    file_size_limit = least(coalesce(file_size_limit, 5242880), 5242880),
    allowed_mime_types = array['image/*', 'application/pdf']::text[]
where id = 'verification-docs';

drop policy if exists verification_docs_insert on storage.objects;
drop policy if exists verification_docs_select on storage.objects;
drop policy if exists verification_docs_update on storage.objects;
drop policy if exists verification_docs_delete on storage.objects;
create policy verification_docs_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);
create policy verification_docs_select on storage.objects
  for select to authenticated
  using (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);
create policy verification_docs_update on storage.objects
  for update to authenticated
  using (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);
create policy verification_docs_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);

create or replace function public.submit_verification_documents(p_paths text[])
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  caller uuid := auth.uid();
  item text;
begin
  if caller is null then
    raise exception 'Authentication required';
  end if;
  if p_paths is null or coalesce(array_length(p_paths, 1), 0) < 1 or array_length(p_paths, 1) > 3 then
    raise exception 'Upload one to three verification documents';
  end if;
  foreach item in array p_paths loop
    if item is null or length(item) > 512 or item !~ ('^' || caller::text || '/[^/].*') then
      raise exception 'Invalid verification document path';
    end if;
  end loop;
  update public.users_profile
  set verification_documents_url = p_paths,
      verification_status = case when verification_status = 'verified' then verification_status else 'pending' end,
      updated_at = now()
  where id = caller;
  if not found then
    raise exception 'Profile not found';
  end if;
  return true;
end;
$$;
revoke all on function public.submit_verification_documents(text[]) from public, anon, authenticated;
grant execute on function public.submit_verification_documents(text[]) to authenticated;

-- Deal submissions calculate commission and bind agent_id from auth.uid().
create or replace function public.submit_agent_deal(p_deal jsonb)
returns public.deals
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  caller uuid := auth.uid();
  profile_row public.users_profile%rowtype;
  result public.deals;
  sale numeric;
  base_rate numeric;
  referral_bonus numeric;
  commission numeric;
  attachments text[];
begin
  if caller is null then
    raise exception 'Authentication required';
  end if;
  if jsonb_typeof(p_deal) <> 'object' then
    raise exception 'Invalid deal payload';
  end if;
  select * into profile_row
  from public.users_profile
  where id = caller and account_status = 'active' and verification_status = 'verified'
  for update;
  if not found then
    raise exception 'Only active verified agents can submit deals';
  end if;
  if nullif(trim(p_deal->>'propertyName'), '') is null
     or nullif(trim(p_deal->>'developerName'), '') is null
     or nullif(trim(p_deal->>'clientName'), '') is null
     or nullif(trim(p_deal->>'unitCode'), '') is null then
    raise exception 'Property, developer, client, and unit are required';
  end if;
  sale := nullif(p_deal->>'saleAmount', '')::numeric;
  if sale is null or sale < 100000 then
    raise exception 'Sale amount must be at least 100000';
  end if;
  if p_deal ? 'attachments' and jsonb_typeof(p_deal->'attachments') <> 'array' then
    raise exception 'Attachments must be an array';
  end if;
  attachments := array(select jsonb_array_elements_text(coalesce(p_deal->'attachments', '[]'::jsonb)));
  base_rate := least(10, greatest(0, coalesce(profile_row.base_commission_rate, 2.5)));
  referral_bonus := least(5, greatest(0, coalesce(profile_row.referral_bonus_rate, 0)));
  commission := least(10, base_rate + referral_bonus);
  insert into public.deals (
    deal_reference, agent_id, property_name, developer_name, client_name, sale_amount,
    unit_code, deal_sheet_photos, additional_documents, commission_rate, base_rate,
    referral_bonus, estimated_commission, status, admin_notes
  ) values (
    'BRX-' || upper(replace(substr(gen_random_uuid()::text, 1, 12), '-', '')),
    caller,
    trim(p_deal->>'propertyName'),
    trim(p_deal->>'developerName'),
    trim(p_deal->>'clientName'),
    sale,
    trim(p_deal->>'unitCode'),
    attachments,
    null,
    commission,
    base_rate,
    referral_bonus,
    sale * commission / 100,
    'submitted',
    nullif(trim(p_deal->>'notes'), '')
  ) returning * into result;
  return result;
end;
$$;
revoke all on function public.submit_agent_deal(jsonb) from public, anon, authenticated;
grant execute on function public.submit_agent_deal(jsonb) to authenticated;
revoke insert on table public.deals from anon, authenticated;

-- Distributed phone verification throttling (three sends per ten minutes/user).
create table if not exists public.phone_verification_rate_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  phone text not null,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 0 check (attempts >= 0),
  updated_at timestamptz not null default now()
);
alter table public.phone_verification_rate_limits enable row level security;
alter table public.phone_verification_rate_limits force row level security;
revoke all on table public.phone_verification_rate_limits from public, anon, authenticated;

create or replace function public.consume_phone_verification_attempt(
  p_user_id uuid,
  p_phone text,
  p_limit integer default 3,
  p_window_seconds integer default 600
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  current_row public.phone_verification_rate_limits%rowtype;
  jwt_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
begin
  if jwt_role <> 'service_role' then
    raise exception 'Service role required';
  end if;
  if p_user_id is null or p_phone is null or p_limit < 1 or p_window_seconds < 1 then
    raise exception 'Invalid rate limit parameters';
  end if;
  select * into current_row
  from public.phone_verification_rate_limits
  where user_id = p_user_id
  for update;
  if not found then
    insert into public.phone_verification_rate_limits(user_id, phone, attempts)
    values (p_user_id, p_phone, 1);
    return true;
  end if;
  if current_row.window_started_at + make_interval(secs => p_window_seconds) <= now() then
    update public.phone_verification_rate_limits
    set phone = p_phone, window_started_at = now(), attempts = 1, updated_at = now()
    where user_id = p_user_id;
    return true;
  end if;
  if current_row.attempts >= p_limit then
    return false;
  end if;
  update public.phone_verification_rate_limits
  set phone = p_phone, attempts = attempts + 1, updated_at = now()
  where user_id = p_user_id;
  return true;
end;
$$;
revoke all on function public.consume_phone_verification_attempt(uuid, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_phone_verification_attempt(uuid, text, integer, integer) to service_role;

-- Renewal RPCs derive actor identity from the JWT. The service role may pass a
-- validated actor id for server-side admin/developer workflows.
create or replace function public.request_property_renewal(
  p_property_id uuid,
  p_actor_role property_renewal_actor,
  p_actor_id uuid default null,
  p_notes text default null
) returns property_renewal_requests
language plpgsql security definer
set search_path = public, extensions
as $$
declare
  listing record;
  result property_renewal_requests;
  message text;
  caller uuid := auth.uid();
  effective_id uuid;
  is_service boolean := coalesce(current_setting('request.jwt.claim.role', true), '') = 'service_role';
begin
  effective_id := case when is_service then p_actor_id else caller end;
  if effective_id is null then raise exception 'Authentication required'; end if;
  select * into listing from properties where id = p_property_id for update;
  if not found then raise exception 'Property % not found', p_property_id; end if;
  if listing.approval_status <> 'approved' then raise exception 'Only approved listings can be renewed (property=%)', p_property_id; end if;
  if p_actor_role = 'admin' then
    if not exists (select 1 from admins where id = effective_id and is_active = true) then raise exception 'Active admin required'; end if;
    update properties set expires_at = greatest(coalesce(listing.expires_at, now()), now()) + interval '3 months', last_renewed_at = now(), renewal_status = 'active', renewal_prompted_at = null, approval_status = 'approved', is_active = true where id = p_property_id returning * into listing;
    insert into property_renewal_requests(property_id, requested_by_role, requested_by_id, status, reviewed_by, reviewed_at, notes) values (p_property_id, 'admin', effective_id, 'approved', effective_id, now(), coalesce(p_notes, 'Renewed directly by admin')) returning * into result;
    message := format('Listing %s renewed by admin', coalesce(listing.property_name, listing.id::text));
    perform log_property_expiration_event(p_property_id, 'admin', effective_id, 'renewal_approved', message);
    perform log_property_expiration_event(p_property_id, 'agent', listing.listed_by_agent_id, 'renewal_approved', message);
    perform log_property_expiration_event(p_property_id, 'developer', listing.developer_id, 'renewal_approved', message);
    perform enqueue_agent_notification(listing.listed_by_agent_id, 'Listing renewed', message, p_property_id);
    return result;
  elsif p_actor_role = 'agent' then
    if listing.listed_by_agent_id is null or listing.listed_by_agent_id <> effective_id then raise exception 'Only the listing agent can request renewal'; end if;
  elsif p_actor_role = 'developer' then
    if not exists (select 1 from developer_accounts where auth_user_id = effective_id and developer_id = listing.developer_id and status = 'active') then raise exception 'Active developer membership required'; end if;
  else
    raise exception 'Invalid renewal actor';
  end if;
  insert into property_renewal_requests(property_id, requested_by_role, requested_by_id, notes) values (p_property_id, p_actor_role, effective_id, p_notes) returning * into result;
  update properties set renewal_status = 'awaiting_admin' where id = p_property_id;
  message := format('Renewal requested by %s for %s', p_actor_role, coalesce(listing.property_name, listing.id::text));
  perform log_property_expiration_event(p_property_id, 'admin', null, 'renewal_request', message);
  perform log_property_expiration_event(p_property_id, 'developer', listing.developer_id, 'renewal_request', message);
  if listing.listed_by_agent_id is not null then perform log_property_expiration_event(p_property_id, 'agent', listing.listed_by_agent_id, 'renewal_request', message); end if;
  return result;
end;
$$;

create or replace function public.review_property_renewal_request(
  p_request_id uuid,
  p_admin_id uuid,
  p_approve boolean,
  p_notes text default null
) returns property_renewal_requests
language plpgsql security definer
set search_path = public, extensions
as $$
declare
  request_row property_renewal_requests%rowtype;
  listing record;
  message text;
  caller uuid := auth.uid();
  effective_admin uuid := case when coalesce(current_setting('request.jwt.claim.role', true), '') = 'service_role' then p_admin_id else caller end;
begin
  if effective_admin is null or not exists (select 1 from admins where id = effective_admin and is_active = true) then raise exception 'Active admin required'; end if;
  select * into request_row from property_renewal_requests where id = p_request_id for update;
  if not found then raise exception 'Renewal request % not found', p_request_id; end if;
  if request_row.status <> 'pending' then return request_row; end if;
  select * into listing from properties where id = request_row.property_id for update;
  if not p_approve then
    update property_renewal_requests set status = 'rejected', reviewed_by = effective_admin, reviewed_at = now(), notes = p_notes where id = p_request_id returning * into request_row;
    update properties set renewal_status = 'expired' where id = request_row.property_id;
    message := format('Renewal rejected for %s', coalesce(listing.property_name, listing.id::text));
    perform log_property_expiration_event(request_row.property_id, 'agent', listing.listed_by_agent_id, 'renewal_rejected', message);
    perform log_property_expiration_event(request_row.property_id, 'developer', listing.developer_id, 'renewal_rejected', message);
    perform enqueue_agent_notification(listing.listed_by_agent_id, 'Renewal rejected', message, request_row.property_id);
    return request_row;
  end if;
  update properties set expires_at = greatest(coalesce(listing.expires_at, now()), now()) + interval '3 months', last_renewed_at = now(), renewal_status = 'active', renewal_prompted_at = null, approval_status = 'approved', is_active = true where id = request_row.property_id returning * into listing;
  update property_renewal_requests set status = 'approved', reviewed_by = effective_admin, reviewed_at = now(), notes = p_notes where id = p_request_id returning * into request_row;
  message := format('Renewal approved for %s', coalesce(listing.property_name, listing.id::text));
  perform log_property_expiration_event(request_row.property_id, 'agent', listing.listed_by_agent_id, 'renewal_approved', message);
  perform log_property_expiration_event(request_row.property_id, 'developer', listing.developer_id, 'renewal_approved', message);
  perform enqueue_agent_notification(listing.listed_by_agent_id, 'Listing renewed', message, request_row.property_id);
  return request_row;
end;
$$;

revoke all on function public.request_property_renewal(uuid, property_renewal_actor, uuid, text) from public, anon;
grant execute on function public.request_property_renewal(uuid, property_renewal_actor, uuid, text) to authenticated;
revoke all on function public.review_property_renewal_request(uuid, uuid, boolean, text) from public, anon;
grant execute on function public.review_property_renewal_request(uuid, uuid, boolean, text) to authenticated;
revoke execute on function public.set_sales_claim_status(uuid, text) from public, anon;
grant execute on function public.set_sales_claim_status(uuid, text) to authenticated;

commit;
